[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
egui = { git = "https://github.com/emilk/egui", rev = "1488ffa35a407653c81d1400483a67e559768878" }
egui-wgpu = { git = "https://github.com/emilk/egui", features = [
    "winit",
], rev = "1488ffa35a407653c81d1400483a67e559768878" }
env_logger = "0.11.5"
log = "0.4.22"
winit = "0.30.5"
nalgebra-glm = { version = "0.19.0", features = [
    "convert-bytemuck",
    "serde-serialize",
] }
wgpu = { version = "22.1.0", default-features = false }
futures = "0.3.30"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { git = "https://github.com/emilk/egui", rev = "1488ffa35a407653c81d1400483a67e559768878" }
pollster = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
egui-winit = { git = "https://github.com/emilk/egui", default-features = false, rev = "1488ffa35a407653c81d1400483a67e559768878" }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.70", features = [
    "Window",
    "Document",
    "HtmlElement",
    "Node",
    "Text",
] }
web-time = "1.1.0"

[features]
default = ["wgpu/default"]
webgl = ["wgpu/webgl"]
webgpu = ["wgpu/webgpu"]
